apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: hello-world-front-end
      docker: {}
      context: hello-world-front-end
    - image: spring-java-hello-world
      jib: {}
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - kubernetes/deployment.yml
    - hello-world-front-end/kubernetes/deployment.yml

profiles:
  - name: dev
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
    build:
      local:
        push: false
      # Generated artifact
      artifacts:
        - image: spring-java-hello-world
          jib: {}
        - image: hello-world-front-end
          docker: {}
          context: hello-world-front-end
    manifests:
      rawYaml:
        - kubernetes/deployment.yml
        - hello-world-front-end/kubernetes/deployment.yml
    portForward:
      - resourceType: service
        resourceName: spring-java-hello-world-service
        port: 8080
        localPort: 9000
      - resourceType: service
        resourceName: hello-world-front-end-service
        port: 8080
        localPort: 9001
  - name: staging
    build:
      local:
        push: false
      artifacts:
        - image: spring-java-hello-world
          jib: {}
        - image: hello-world-front-end
          docker: {}
          context: hello-world-front-end
    manifests:
      rawYaml:
        - kubernetes/gke-deployment.yml
        - hello-world-front-end/kubernetes/gke-deployment.yml
    deploy:
      kubectl: {}
